-- CreateEnum
CREATE TYPE "QuestionFormat" AS ENUM ('MULTIPLE_CHOICE', 'FILL_IN_THE_GAP');

-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "format" "QuestionFormat" NOT NULL DEFAULT 'MULTIPLE_CHOICE',
ALTER COLUMN "optionA" DROP NOT NULL,
ALTER COLUMN "optionB" DROP NOT NULL,
ALTER COLUMN "optionC" DROP NOT NULL,
ALTER COLUMN "optionD" DROP NOT NULL;
